package model;

// Generated Apr 1, 2016 2:21:00 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * TblAngsuran generated by hbm2java
 */
public class TblAngsuran implements java.io.Serializable {

	private BigDecimal angsuranId;
	private TblContract tblContract;
	private BigDecimal tenor;
	private Date tanggal;

	public TblAngsuran() {
	}

	public TblAngsuran(BigDecimal angsuranId, TblContract tblContract) {
		this.angsuranId = angsuranId;
		this.tblContract = tblContract;
	}

	public TblAngsuran(BigDecimal angsuranId, TblContract tblContract,
			BigDecimal tenor, Date tanggal) {
		this.angsuranId = angsuranId;
		this.tblContract = tblContract;
		this.tenor = tenor;
		this.tanggal = tanggal;
	}

	public BigDecimal getAngsuranId() {
		return this.angsuranId;
	}

	public void setAngsuranId(BigDecimal angsuranId) {
		this.angsuranId = angsuranId;
	}

	public TblContract getTblContract() {
		return this.tblContract;
	}

	public void setTblContract(TblContract tblContract) {
		this.tblContract = tblContract;
	}

	public BigDecimal getTenor() {
		return this.tenor;
	}

	public void setTenor(BigDecimal tenor) {
		this.tenor = tenor;
	}

	public Date getTanggal() {
		return this.tanggal;
	}

	public void setTanggal(Date tanggal) {
		this.tanggal = tanggal;
	}

}
