package model;

// Generated Apr 1, 2016 2:21:00 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TblCustomerAlamat generated by hbm2java
 */
public class TblCustomerAlamat implements java.io.Serializable {

	private BigDecimal customerAlamatId;
	private TblAlamatTagih tblAlamatTagih;
	private TblCustomer tblCustomer;

	public TblCustomerAlamat() {
	}

	public TblCustomerAlamat(BigDecimal customerAlamatId,
			TblAlamatTagih tblAlamatTagih, TblCustomer tblCustomer) {
		this.customerAlamatId = customerAlamatId;
		this.tblAlamatTagih = tblAlamatTagih;
		this.tblCustomer = tblCustomer;
	}

	public BigDecimal getCustomerAlamatId() {
		return this.customerAlamatId;
	}

	public void setCustomerAlamatId(BigDecimal customerAlamatId) {
		this.customerAlamatId = customerAlamatId;
	}

	public TblAlamatTagih getTblAlamatTagih() {
		return this.tblAlamatTagih;
	}

	public void setTblAlamatTagih(TblAlamatTagih tblAlamatTagih) {
		this.tblAlamatTagih = tblAlamatTagih;
	}

	public TblCustomer getTblCustomer() {
		return this.tblCustomer;
	}

	public void setTblCustomer(TblCustomer tblCustomer) {
		this.tblCustomer = tblCustomer;
	}

}
