package model;

// Generated Apr 1, 2016 2:21:00 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TblCustomer generated by hbm2java
 */
public class TblCustomer implements java.io.Serializable {

	private BigDecimal customerId;
	private String customerName;
	private Set<TblContract> tblContracts = new HashSet<TblContract>(0);
	private TblPhone tblPhone;
	private Set<TblCustomerAlamat> tblCustomerAlamats = new HashSet<TblCustomerAlamat>(
			0);

	public TblCustomer() {
	}

	public TblCustomer(BigDecimal customerId, String customerName) {
		this.customerId = customerId;
		this.customerName = customerName;
	}

	public TblCustomer(BigDecimal customerId, String customerName,
			Set<TblContract> tblContracts, TblPhone tblPhone,
			Set<TblCustomerAlamat> tblCustomerAlamats) {
		this.customerId = customerId;
		this.customerName = customerName;
		this.tblContracts = tblContracts;
		this.tblPhone = tblPhone;
		this.tblCustomerAlamats = tblCustomerAlamats;
	}

	public BigDecimal getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(BigDecimal customerId) {
		this.customerId = customerId;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public Set<TblContract> getTblContracts() {
		return this.tblContracts;
	}

	public void setTblContracts(Set<TblContract> tblContracts) {
		this.tblContracts = tblContracts;
	}

	public TblPhone getTblPhone() {
		return this.tblPhone;
	}

	public void setTblPhone(TblPhone tblPhone) {
		this.tblPhone = tblPhone;
	}

	public Set<TblCustomerAlamat> getTblCustomerAlamats() {
		return this.tblCustomerAlamats;
	}

	public void setTblCustomerAlamats(Set<TblCustomerAlamat> tblCustomerAlamats) {
		this.tblCustomerAlamats = tblCustomerAlamats;
	}

}
