package model;

// Generated Apr 1, 2016 2:21:00 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * TblPhone generated by hbm2java
 */
public class TblPhone implements java.io.Serializable {

	private BigDecimal phoneId;
	private TblCustomer tblCustomer;
	private String phoneNo;

	public TblPhone() {
	}

	public TblPhone(TblCustomer tblCustomer) {
		this.tblCustomer = tblCustomer;
	}

	public TblPhone(TblCustomer tblCustomer, String phoneNo) {
		this.tblCustomer = tblCustomer;
		this.phoneNo = phoneNo;
	}

	public BigDecimal getPhoneId() {
		return this.phoneId;
	}

	public void setPhoneId(BigDecimal phoneId) {
		this.phoneId = phoneId;
	}

	public TblCustomer getTblCustomer() {
		return this.tblCustomer;
	}

	public void setTblCustomer(TblCustomer tblCustomer) {
		this.tblCustomer = tblCustomer;
	}

	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

}
